image: node:16-alpine

stages:
 - deploy

deploy_npm:
 stage: deploy
 only:
  - main
 tags:
 - testing
 script:
 - npm config set registry https://registry.npm.taobao.org
 - npm install
 - npm run build
 - echo "@frontend-lib:registry=http://192.168.10.10/api/v4/projects/${CI_PROJECT_ID}/packages/npm/" > .npmrc
 - echo "//192.168.10.10/api/v4/projects/${CI_PROJECT_ID}/packages/npm/:_authToken=${NPM_TOKEN}" >> .npmrc
 - npm publish
